from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('VL53L0X', src, depend = ['PKG_USING_VL53L0X'], CPPPATH = CPPPATH)

Return('group')
